'use client';

import type { LeaseAnalysisResult } from '@/types';
import { FLAG_CONFIG } from '@/lib/utils';

type Props = {
  result: LeaseAnalysisResult;
};

export default function ActionPlan({ result }: Props) {
  // Gather unique actions, prioritizing critical first
  const ordered = [
    ...result.flags.filter((f) => f.type === 'critical'),
    ...result.flags.filter((f) => f.type === 'warning'),
    ...result.flags.filter((f) => f.type === 'info'),
  ];

  if (ordered.length === 0) return null;

  return (
    <div className="bg-bg-card border border-border-base rounded-2xl p-6 shadow-card">
      <div className="flex items-center gap-3 mb-5">
        <div className="w-8 h-8 rounded-lg bg-text-primary flex items-center justify-center">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="9 11 12 14 22 4" />
            <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
          </svg>
        </div>
        <div>
          <h2 className="font-serif font-bold text-lg text-text-primary">Action Plan</h2>
          <p className="text-text-muted text-xs">Steps to protect yourself before signing</p>
        </div>
      </div>

      <ol className="space-y-3">
        {ordered.map((flag, i) => {
          const cfg = FLAG_CONFIG[flag.type];
          return (
            <li
              key={i}
              className="flex items-start gap-3 p-3 rounded-lg border animate-fade-in"
              style={{
                borderColor: cfg.borderColor,
                backgroundColor: cfg.bgColor,
                animationDelay: `${i * 40}ms`,
                animationFillMode: 'both',
              }}
            >
              {/* Step number */}
              <span
                className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white"
                style={{ backgroundColor: cfg.color }}
              >
                {i + 1}
              </span>

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-0.5">
                  <span className="text-xs font-bold uppercase tracking-wider" style={{ color: cfg.color }}>
                    {cfg.label}
                  </span>
                  <span className="text-xs text-text-muted font-mono">{flag.section}</span>
                </div>
                <p className="text-sm font-semibold text-text-primary mb-1">{flag.title}</p>
                <p className="text-sm text-text-secondary leading-relaxed">{flag.action}</p>
              </div>
            </li>
          );
        })}
      </ol>

      {/* Legal disclaimer */}
      <div className="mt-5 pt-4 border-t border-border-base">
        <p className="text-xs text-text-muted leading-relaxed">
          <span className="font-semibold text-text-secondary">Disclaimer:</span>{' '}
          This analysis is generated by AI and is for informational purposes only.
          It does not constitute legal advice. Always consult a qualified attorney
          before signing any lease agreement.
        </p>
      </div>
    </div>
  );
}
